{% set version = "2.3.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-extremevalues
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/extremevalues_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/extremevalues/extremevalues_{{ version }}.tar.gz
  sha256: a64bf0874d0dd14f1dc82e4d3ba02c148f3791981d93fa19c878ecfa7f515046

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:

  host:
    - r-base
    - r-gwidgets
    - r-gwidgetstcltk
  run:
    - r-base
    - r-gwidgets
    - r-gwidgetstcltk

test:
  commands:
    - $R -e "library('extremevalues')"           # [not win]
    - "\"%R%\" -e \"library('extremevalues')\""  # [win]

about:
  home: https://www.github.com/markvanderloo/extremevalues
  license: GPL-2
  summary: Detect outliers in one-dimensional data.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: extremevalues
# Description: Detect outliers in one-dimensional data.
# Version: 2.3.2
# Date: 2016-01-05
# Title: Univariate Outlier Detection
# Author: Mark van der Loo <mark.vanderloo@gmail.com>
# Maintainer: Mark van der Loo <mark.vanderloo@gmail.com>
# Depends: R (>= 2.8.0)
# Imports: gWidgets, gWidgetstcltk, utils, stats, graphics
# License: GPL-2
# URL: https://www.github.com/markvanderloo/extremevalues
# Repository: CRAN
# NeedsCompilation: no
# Packaged: 2016-01-20 09:09:37 UTC; mark
# Date/Publication: 2016-01-20 10:29:56
